# Create Certificate


@host =localhost:4000


### User Registration 
POST /create-certificate HTTP/1.1
Host: localhost:4000
Content-Type: application/json
Content-Length: 217

{
    "studentID": "student123",
    "studentName": "John Doe",
    "providerID": "provider123",
    "providerName": "CertificateProvider Inc.",
    "course": "Blockchain Fundamentals",
    "issueDate": "2022-01-01"
}



 

# Share Certificate

PUT /share-certificate/student123 HTTP/1.1
Host: {{host}}
Content-Type: application/json


# Verify Certificate

PUT /verify-certificate/provider123/student123 HTTP/1.1
Host: {{host}}
Content-Type: application/json


# Get All Certificates

PUT /verify-certificate/provider123/student123 HTTP/1.1
Host: {{host}}
Content-Type: application/json


# Get Single Certificate

GET /get-certificate/student123 HTTP/1.1
Host: {{host}}
