test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      number: 1
    rounds: 
      - label: Verify Certificate 
        description: Certificate Verification 
        txDuration: 60
        rateControl:
          type: fixed-rate
          opts:
            tps: 500
        workload:
          module: workload/verifyCertificate.js
          arguments:
            assets: 2
            contractId: basic